# Generated by Django 2.2.5 on 2019-11-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20191029_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(blank=True, max_length=600)),
                ('starting_bid', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
