# Generated by Django 2.2.5 on 2019-11-20 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_auto_20191118_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='auction_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='balance',
        ),
        migrations.AddField(
            model_name='bid',
            name='item_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.Item'),
        ),
        migrations.AddField(
            model_name='bid',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='BidHistory',
        ),
    ]
