# Generated by Django 2.2.5 on 2019-11-22 23:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_auto_20191122_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 22, 23, 14, 0, 617996, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='silentauction',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 23, 3, 14, 0, 617996, tzinfo=utc), verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='silentauction',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 22, 23, 14, 0, 617996, tzinfo=utc), verbose_name='Start Time'),
        ),
    ]
