# Generated by Django 2.2.5 on 2019-11-25 21:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0011_auto_20191122_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 25, 21, 31, 43, 47926, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='silentauction',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 1, 31, 43, 44309, tzinfo=utc), verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='silentauction',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Time'),
        ),
    ]
