# Generated by Django 2.2.5 on 2019-11-25 21:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_auto_20191125_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 25, 21, 58, 2, 483192, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='silentauction',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 1, 58, 2, 483192, tzinfo=utc), verbose_name='End Time'),
        ),
    ]
