# Generated by Django 2.2.5 on 2019-11-25 22:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0013_auto_20191125_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 25, 22, 6, 31, 389998, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='silentauction',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 2, 6, 31, 389998, tzinfo=utc), verbose_name='End Time'),
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
