# Generated by Django 2.2.5 on 2019-11-25 22:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0014_auto_20191125_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 25, 22, 45, 25, 214036, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='silentauction',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 2, 45, 25, 210037, tzinfo=utc), verbose_name='End Time'),
        ),
    ]
