# Generated by Django 2.2.5 on 2019-11-27 05:54

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0016_auto_20191125_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bid_on',
            field=models.ManyToManyField(blank=True, related_name='bid_on', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='silentauction',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 9, 54, 49, 460819, tzinfo=utc), verbose_name='End Time'),
        ),
    ]
