# Generated by Django 2.2.5 on 2019-12-04 16:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0017_auto_20191126_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silentauction',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 4, 20, 43, 2, 524829, tzinfo=utc), verbose_name='End Time'),
        ),
    ]
