# Generated by Django 2.2.5 on 2019-12-06 17:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0018_auto_20191204_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silentauction',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 6, 21, 56, 16, 770347, tzinfo=utc), verbose_name='End Time'),
        ),
    ]
