# Generated by Django 2.1.5 on 2019-04-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lbs_to_t_oz', models.DecimalField(decimal_places=6, default=0.68587, max_digits=6)),
                ('t_oz_to_lbs', models.DecimalField(decimal_places=2, default=14.58, max_digits=4)),
            ],
        ),
    ]
