# Generated by Django 2.1.5 on 2019-04-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitconv', '0002_auto_20190403_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convfactor',
            name='lbs_to_t_oz',
            field=models.DecimalField(decimal_places=4, default=14.5833, max_digits=6),
        ),
    ]
